Repository DenverCoder1/jct-discord-bot, pull requests merged in 2021-01, with the labels that each got.

#13 added structure for each module to have many files
  Contributing.md
  bot.py
  modules/ping/responses.txt
  modules/ping_cog.py
Labels: documentation

#28 File restructure
  Contributing.md
  bot.py
  modules/piglatin/__init__.py
  modules/piglatin/cog.py
  modules/ping/cog.py
Labels: refactoring

#29 added a style guide
  README.md
  bot.py
  contributing.md
  modules/piglatin/cog.py
  modules/piglatin/translate.py
  modules/ping/cog.py
  style_guide.md
Labels: documentation

#33 supress welcome for bots and give them bot tag
  bot.py
  modules/new_user/IDs.csv
  modules/new_user/cog.py
  modules/new_user/new_user.py
  modules/role_tag/member.py
Labels: enhancement

#36 Added contributor list action
  .github/workflows/contributor_list.yml
  README.md
  contributing.md
Labels: documentation

#39 FriendlyError, organised error logging & handling
  contributing.md
  modules/error/cog.py
  modules/error/error_handler.py
  modules/error/error_logger.py
  modules/error/friendly_error.py
  modules/error_log/cog.py
  modules/error_log/error_handler.py
  modules/new_user/cog.py
  modules/new_user/utils.py
  modules/piglatin/cog.py
  modules/ping/cog.py
  modules/role_tag/cog.py
  modules/utils/utils.py
  utils/ids.csv
  utils/utils.py
Labels: enhancement, refactoring

#40 some errors werent getting reported in channel
  modules/error/cog.py
  modules/error/error_logger.py
Labels: bug

#44 Welcoming in the welcome channel when assigned role
  bot.py
  modules/new_user/utils.py
Labels: enhancement

#48 Added markdown command
  modules/formatting/cog.py
  modules/formatting/formatting_tip.py
  modules/formatting/tip_formatter.py
  modules/search/cog.py
  utils/utils.py
Labels: enhancement

#52 fixed #51
  modules/role_tag/cog.py
  modules/role_tag/member.py
Labels: bug

#56 Join to off topic, suppress some errors from log channel
  modules/error/error_handler.py
  modules/join/assigner.py
  modules/join/cog.py
  utils/ids.csv
Labels: bug

#58 Teacher emails
  bot.py
  config.py
  modules/error/friendly_error.py
  modules/teacher_emails/cog.py
  modules/teacher_emails/email_finder.py
  modules/teacher_emails/professor.py
  modules/teacher_emails/professor_embedder.py
  modules/teacher_emails/queries/get_professors.sql
  modules/teacher_emails/queries/search_channel.sql
  modules/teacher_emails/queries/search_kw.sql
  modules/teacher_emails/queries/search_member.sql
  modules/teacher_emails/teacher_weights.py
Labels: enhancement

#60 left instead of inner join includes more
  modules/teacher_emails/email_finder.py
  modules/teacher_emails/queries/search_kw.sql
Labels: bug

#61 left join when retrieving emails
  modules/teacher_emails/cog.py
  modules/teacher_emails/queries/get_professors.sql
Labels: bug

#62 add emails to existing professors
  modules/teacher_emails/cog.py
  modules/teacher_emails/email_adder.py
  modules/teacher_emails/email_finder.py
  modules/teacher_emails/professor.py
  modules/teacher_emails/professor_embedder.py
  modules/teacher_emails/queries/add_email.sql
  modules/teacher_emails/queries/get_professors.sql
  modules/teacher_emails/queries/search_channel.sql
  modules/teacher_emails/queries/search_kw.sql
  modules/teacher_emails/queries/search_member.sql
  modules/teacher_emails/sql_path.py
Labels: enhancement

#63 renamed everything
  modules/email_registry/cog.py
  modules/email_registry/email_adder.py
  modules/email_registry/email_finder.py
  modules/email_registry/person.py
  modules/email_registry/person_embedder.py
  modules/email_registry/queries/add_email.sql
  modules/email_registry/queries/get_people.sql
  modules/email_registry/queries/search_channel.sql
  modules/email_registry/queries/search_kw.sql
  modules/email_registry/queries/search_member.sql
  modules/email_registry/sql_path.py
  modules/email_registry/weighted_set.py
  modules/teacher_emails/email_finder.py
  modules/teacher_emails/professor.py
  modules/teacher_emails/professor_embedder.py
  modules/teacher_emails/queries/add_email.sql
  modules/teacher_emails/sql_path.py
  modules/teacher_emails/teacher_weights.py
Labels: refactoring

#67 Teacher emails
  modules/email_registry/categoriser.py
  modules/email_registry/cog.py
  modules/email_registry/email_adder.py
  modules/email_registry/email_finder.py
  modules/email_registry/person.py
  modules/email_registry/person_adder.py
  modules/email_registry/person_finder.py
  modules/email_registry/queries/add_email.sql
  modules/email_registry/queries/add_person.sql
  modules/email_registry/queries/categorise_person.sql
  modules/email_registry/queries/decategorise_person.sql
  modules/email_registry/queries/get_people.sql
  modules/email_registry/queries/remove_email.sql
  modules/email_registry/queries/search_channel.sql
  modules/email_registry/queries/search_kw.sql
  modules/email_registry/queries/search_member.sql
  modules/email_registry/sql_path.py
  modules/error/error_handler.py
  modules/error/quiet_warning.py
  utils/sql_fetcher.py
  utils/utils.py
Labels: bug, enhancement
