Repository DenverCoder1/jct-discord-bot, pull requests merged in 2021-04, with the labels that each got.

#106 Add course channel
  .DS_Store
  .gitignore
  config.py
  modules/calendar/calendar_creator.py
  modules/calendar/calendar_embedder.py
  modules/calendar/calendar_finder.py
  modules/calendar/cog.py
  modules/calendar/course_mentions.py
  modules/course_management/cog.py
  modules/course_management/course_adder.py
  modules/course_management/queries/add_course.sql
  modules/course_management/queries/add_label.sql
  modules/create_class/class_.py
  modules/create_class/cog.py
  modules/email_registry/categoriser.py
  modules/email_registry/cog.py
  modules/email_registry/email_adder.py
  modules/email_registry/person_adder.py
  modules/email_registry/person_embedder.py
  modules/email_registry/person_finder.py
  modules/error/friendly_error.py
  modules/formatting/cog.py
  modules/join/assigner.py
  modules/join/cog.py
  modules/xkcd/cog.py
  modules/xkcd/xkcd_embedder.py
  utils/__init__.py
  utils/campus/campus.py
  utils/embedder.py
  utils/ids.csv
  utils/sql_fetcher.py
  utils/utils.py
Labels: enhancement

#107 Delete courses with ++courses.delete
  modules/calendar/calendar_creator.py
  modules/calendar/calendar_finder.py
  modules/calendar/course_mentions.py
  modules/course_management/cog.py
  modules/course_management/course_adder.py
  modules/course_management/course_deleter.py
  modules/course_management/queries/delete_course.sql
  modules/create_class/class_.py
  modules/email_registry/categoriser.py
  modules/email_registry/email_adder.py
  modules/email_registry/person_adder.py
  modules/email_registry/person_finder.py
  modules/error/friendly_error.py
  modules/join/assigner.py
  utils/campus/campus.py
  utils/sql_fetcher.py
  utils/utils.py
Labels: enhancement

#108 ping
  modules/ping/cog.py
Labels: enhancement

#109 /email command and support for slash commands in friendly error
  .DS_Store
  modules/email_registry/cog.py
  modules/email_registry/person_embedder.py
  modules/email_registry/person_finder.py
  modules/email_registry/queries/search_by_name.sql
  modules/email_registry/queries/search_kw.sql
  modules/error/cog.py
  modules/error/friendly_error.py
  modules/join/cog.py
  modules/join/join_parser.py
Labels: enhancement, refactoring

#111 add and remove emails slash commands
  modules/calendar/course_mentions.py
  modules/course_management/cog.py
  modules/email_registry/categoriser.py
  modules/email_registry/cog.py
  modules/email_registry/email_adder.py
  modules/email_registry/person_adder.py
  modules/email_registry/person_embedder.py
  modules/email_registry/person_finder.py
  modules/email_registry/queries/add_person.sql
  modules/email_registry/queries/search_by_name.sql
  modules/email_registry/queries/search_channel.sql
  modules/email_registry/queries/search_email.sql
  modules/email_registry/queries/search_member.sql
  utils/mention.py
  utils/utils.py
Labels: enhancement, refactoring

#117 /email person add
  modules/calendar/course_mentions.py
  modules/course_management/cog.py
  modules/email_registry/categoriser.py
  modules/email_registry/cog.py
  modules/email_registry/email_adder.py
  modules/email_registry/person_adder.py
  modules/email_registry/person_embedder.py
  modules/email_registry/person_finder.py
  modules/email_registry/queries/add_person.sql
  modules/email_registry/queries/search_by_name.sql
  modules/email_registry/queries/search_channel.sql
  modules/email_registry/queries/search_email.sql
  modules/email_registry/queries/search_member.sql
  utils/mention.py
  utils/utils.py
Labels: enhancement

#118 slash commands to link/unlink people to/from courses
  modules/email_registry/categoriser.py
  modules/email_registry/cog.py
  modules/email_registry/person_finder.py
Labels: enhancement

#119 /search (refactored), /logs, /xkcd, /course, and /markdown (refactored)
  modules/course_management/cog.py
  modules/course_management/course_adder.py
  modules/course_management/queries/add_label.sql
  modules/email_registry/email_adder.py
  modules/email_registry/person_finder.py
  modules/error/cog.py
  modules/error/error_logger.py
  modules/error/friendly_error.py
  modules/formatting/cog.py
  modules/formatting/formatting_tip.py
  modules/formatting/tip_formatter.py
  modules/markdown/cog.py
  modules/markdown/formatting_tip.py
  modules/markdown/tip_formatter.py
  modules/search/cog.py
  modules/search/search_functions.py
  modules/xkcd/cog.py
Labels: enhancement, refactoring

#122 add new class roles to their campus channel
  modules/create_class/class_.py
  modules/create_class/class_channel_creator.py
  utils/campus/campus.py
  utils/campus/queries/get_campuses.sql
Labels: bug, enhancement

#124 delete help and piglatin cogs
  modules/help/cog.py
  modules/help/help_command.py
  modules/piglatin/cog.py
  modules/piglatin/translate.py
Labels: refactoring

#125 Calendar cog slash commands
  database/campus/queries/get_campus.sql
  modules/calendar/calendar_embedder.py
  modules/calendar/calendar_finder.py
  modules/calendar/calendar_service.py
  modules/calendar/cog.py
  modules/calendar/queries/get_group_roles.sql
  modules/join/cog.py
  utils/utils.py
Labels: enhancement

#127 Fuzzy calendar search
  modules/calendar/calendar_service.py
  requirements.txt
Labels: enhancement

#130 removed super outdated details from readme
  README.md
Labels: documentation

#134 made person object implement eq and hash
  database/campus/campus.py
  database/group/group.py
  database/person/person.py
  modules/calendar/calendar_creator.py
  modules/calendar/cog.py
  modules/course_management/course_adder.py
  modules/create_group/new_group.py
  modules/email_registry/categoriser.py
  modules/email_registry/email_adder.py
  modules/email_registry/person_embedder.py
  modules/graduation/graduation.py
  modules/join/cog.py
Labels: bug, documentation, refactoring

#135 Refactor calendar and increase event description max
  modules/calendar/calendar.py
  modules/calendar/calendar_embedder.py
  modules/calendar/calendar_finder.py
  modules/calendar/calendar_service.py
  modules/calendar/class_parse_error.py
  modules/calendar/class_role_error.py
  modules/calendar/cog.py
  modules/calendar/event.py
  modules/calendar/queries/get_group_roles.sql
  modules/calendar/queries/search_calendar.sql
  modules/calendar/queries/search_campus.sql
Labels: refactoring

#139 changed static classes to modules
  modules/course_management/cog.py
  modules/course_management/course_adder.py
  modules/course_management/course_deleter.py
  modules/email_registry/categoriser.py
  modules/email_registry/cog.py
  modules/email_registry/email_adder.py
  modules/email_registry/person_adder.py
  modules/email_registry/person_finder.py
Labels: refactoring

#146 friendly errors can be sent after slash reply
  modules/error/friendly_error.py
Labels: bug

#145 Move end dates along with start date when end date isn't specified
  modules/calendar/calendar.py
  modules/calendar/calendar_service.py
  modules/calendar/event.py
Labels: bug

#147 made ping say whose computer its running on
  modules/ping/cog.py
Labels: enhancement

#148 Dates are converted to Jerusalem time when event object is created
  modules/calendar/calendar_service.py
  modules/calendar/event.py
Labels: enhancement

#149 Event md links
  modules/calendar/calendar_embedder.py
  modules/calendar/calendar_service.py
  modules/calendar/event.py
  modules/calendar/html_parser.py
Labels: enhancement

#151 Added back title text and "..."
  modules/calendar/calendar_embedder.py
  modules/calendar/calendar_service.py
  modules/calendar/html_parser.py
Labels: enhancement

#152 Add variable for old details when updating event
  modules/calendar/cog.py
Labels: enhancement

#159 Fix calendar skipping events and calendar update breaking links
  modules/calendar/calendar_embedder.py
  modules/calendar/calendar_service.py
  modules/calendar/cog.py
  requirements.txt
  utils/utils.py
Labels: bug

#160 moved ppl search to db and fuzzy match
  .gitignore
  database/person/person.py
  database/person/queries/search_channel.sql
  database/person/queries/search_email.sql
  database/person/queries/search_people.sql
  modules/email_registry/person_finder.py
  modules/email_registry/queries/search_by_name.sql
  modules/email_registry/weighted_set.py
Labels: enhancement

#166 Calendar md fix
  modules/calendar/calendar_embedder.py
  modules/calendar/calendar_service.py
  modules/calendar/html_parser.py
  modules/calendar/md_html_converter.py
  requirements.txt
Labels: bug, enhancement

#170 Limit character counts in embeds
  modules/calendar/calendar_embedder.py
  modules/channel_opting/channel_message_manager.py
  modules/email_registry/person_embedder.py
  modules/xkcd/xkcd_embedder.py
  utils/embedder.py
  utils/utils.py
Labels: enhancement

#176 several bug fixes in channel directory on channel delete
  database/channel_message/channel_message.py
  modules/channel_opting/channel_message_manager.py
  utils/utils.py
Labels: bug

#175 various bug fixes in join command
  modules/join/cog.py
  modules/join/queries/get_role.sql
  modules/new_user/greeter.py
Labels: bug
